name: clockify_api
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/ack43/clockify_api

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
