name: clockify_api
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/ack43/clockify_api

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  chopper: ^8.1.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  dotenv: ^4.2.0
  envied: ^1.1.1
  json_serializable: ^6.9.4
  lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.24.0
